---
title: "3_31_2020_Winslow_Thesis_Poisson_Model"
author: "James Winslow"
date: "4/1/2020"
output: pdf_document
---
```{r Import_Data}
source("Winslow_Functions.R")

# this function creates a global object called thesis_data #
# make sure this isn't problematic since using '<<-' isn't a great habit #

import_data("local")
```

```{r}
source("Winslow_Functions.R")
library(dplyr)
library(reshape)

# this function creates a global object called Reshaped & cast_thesis #
# make sure this isn't problematic since using '<<-' isn't a great habit #

clean_data(thesis_data)

```


```{r}
# Now, we attempt to code the likelihood function and apply to the data
# let's look at the data to make sure it's what we think it is #
# head(cast_thesis)

# make a copy of the data for this next bit #
simple_model <- cast_thesis

# rename the variables so it's clear what we are using them for in the simple
# model
simple_model <- `colnames<-`(simple_model, c("id","time.to.death","n.events","dead"))
```
We want to construct a poisson model for the number of infections observed up to a certain time. By imposing an offset, we can interpret the model as a rate instead of a count. This is beneficial to manage the variable start times that subjects may have  

$log(\lambda_{x}) = log(t_{x}) + \beta^{'}_{0} + \beta^{x}_{1}$ \newline
where $log(t_{x})$ is the offset.

```{r}
# We have been getting some weird results for the poisson, so we need to look at # what is going on
MRN_table <- as.data.frame(table(thesis_data$MRN))

table(MRN_table$Freq)

summary(simple_model$n.events)
```

```{r}

# the model we want to use has a poisson component which will link to the survival model via the fraily (random effect) #
# this chunk does some diagnostics to see how well event count fits pois dist #
library(car)
library(MASS)

pois_model <- simple_model


# running poisson model #
## load lme4 package
library(lme4)

pois_model$log.time <- log(pois_model$time.to.death)
pois_model$log.events <- log(pois_model$n.events)


fish <- glm(n.events ~ log.time, family = poisson(link = "log"),
              data  = pois_model)


summary(fish)
```

