---
title: "Data Exploration: Recurrent VPIs with informative death with cluster (hospital) effects"
author: "Jimmy Winslow"
date: "January 10, 2020"
output: pdf_document
---

```{r Import_Data}
library(dplyr)
library(reshape)
source("Winslow_Functions.R")

# this function creates a global object called thesis_data #
# make sure this isn't problematic since using '<<-' isn't a great habit #

import_data("local")


# this function creates a global object called Reshaped & cast_thesis #
# make sure this isn't problematic since using '<<-' isn't a great habit #

clean_data(thesis_data)
clean_up(Reshaped)
```



```{r}
# Look at organ distribution #

plotorgan <- ggplot(Reshaped, aes(x=organ,fill = factor(organ))) + geom_bar(aes(y = stat(count)))

plotorgan + labs(x = "Organ", y = "Count", fill = 'Organ') + geom_text(stat='count', aes(label=..count..), vjust=-1, size = 3)

```

```{r}
# Look at gender distribution #
plotgender <- ggplot(Reshaped, aes(x=gender,fill = factor(gender))) + geom_bar(aes(y = stat(count)))

plotgender + labs(x = "gender", y = "Count", fill = 'gender') + geom_text(stat='count', aes(label=..count..), vjust=-1, size = 3)
```
# year 
```{r}
# Look at year distribution #

plotyear <- ggplot(Reshaped, aes(x=year,fill = factor(year))) + geom_bar(aes(y = stat(count)))

plotyear + labs(x = "year", y = "Count", fill = 'year') + geom_text(stat='count', aes(label=..count..), vjust=-1, size = 3)
```
# lt2
```{r}
# Look at lt2 distribution #


plotlt2 <- ggplot(Reshaped, aes(x=lt2,fill = factor(lt2))) + geom_bar(aes(y = stat(count)))

plotlt2 + labs(x = "lt2", y = "Count", fill = 'lt2') + geom_text(stat='count', aes(label=..count..), vjust=-1, size = 3)
```
# race
```{r}
idrace <- dat[c('id','race')]

Uniqueidrace <- unique(idrace)


testingstuff <- as.data.frame(table(Uniqueidrace$id))

mult_race_listed <- subset(testingstuff, testingstuff$Freq != 1)

dim(mult_race_listed)




race.first <- idrace[match(unique(idrace$id), idrace$id),]
dim(race.first)
# this gets us the right dimension but doesn't match the paper results. So pulling the first occurence of race doesn't work

rawr <- thesis_data[c('id','race')]
unique(rawr)

subset(thesis_data, thesis_data$id==10000701011)
subset(Reshaped, Reshaped$id==10000701011)

annoying_dan <- as.data.frame(table(rawr$id)) 
mult_race <- subset(annoying_dan, annoying_dan$Freq != 1)
# okay so original data does 

plotlt2 <- ggplot(race.first, aes(x=race,fill = factor(race))) + geom_bar(aes(y = stat(count)))

plotlt2 + labs(x = "race", y = "Count", fill = 'race') + geom_text(stat='count', aes(label=..count..), vjust=-1, size = 3)

```
# quarter
```{r}
# Look at lt2 distribution #
# Do we need to group by id first? #
idquarter <- dat[c('id','quarter')]

Uniqueidquarter <- unique(idquarter)
table(Uniqueidquarter$quarter)


plotquarter <- ggplot(Uniqueidquarter, aes(x=quarter,fill = factor(quarter))) + geom_bar(aes(y = stat(count)))

plotquarter + labs(x = "quarter", y = "Count", fill = 'quarter') + geom_text(stat='count', aes(label=..count..), vjust=-1, size = 3)
```

# year
```{r}
# Look at lt2 distribution #
# Do we need to group by id first? #
idyear <- dat[c('id','year')]

Uniqueidyear <- unique(idyear)
table(Uniqueidyear$year)


plotyear <- ggplot(Uniqueidyear, aes(x=year,fill = factor(year))) + geom_bar(aes(y = stat(count)))

plotyear + labs(x = "year", y = "Count", fill = 'year') + geom_text(stat='count', aes(label=..count..), vjust=-1, size = 3)
```

# days
```{r}
# Look at days distribution #
# Do we need to group by id first? #
iddays <- dat[c('id','days')]

Uniqueiddays <- unique(iddays)
summary(Uniqueiddays$days)


```
# event
```{r}
# Look at event distribution #
# Do we need to group by id first? #
idevent <- dat[c('id','event')]

Uniqueidevent <- unique(idevent)
table(Uniqueidevent$event)

# length(Uniqueidorgan$id)

plotevent <- ggplot(Uniqueidevent, aes(x=event,fill = factor(event))) + geom_bar(aes(y = stat(count)))

plotevent + labs(x = "event", y = "Count", fill = 'event') + geom_text(stat='count', aes(label=..count..), vjust=-1, size = 3)
```
# death
```{r}
# Look at death distribution #
# Do we need to group by id first? #
iddeath <- dat[c('id','death')]

Uniqueiddeath <- unique(iddeath)
table(Uniqueiddeath$death)

# length(Uniqueidorgan$id)

plotdeath <- ggplot(Uniqueiddeath, aes(x=death,fill = factor(death))) + geom_bar(aes(y = stat(count)))

plotdeath + labs(x = "death", y = "Count", fill = 'death') + geom_text(stat='count', aes(label=..count..), vjust=-1, size = 3)
```
# start
```{r}
# Look at start distribution #
# Do we need to group by id first? #
idstart <- dat[c('id','start')]
head(idstart)
Uniqueidstart <- unique(idstart)

summary(Uniqueidstart)
 
```
```{r}
# we need to combine the variables by unique id#
library(dplyr)
dat.events <- 'colnames<-' (dat.events, c("id","events"))

good_tab <- merge(dat.events,Uniqueidlt2, by = "id") 
  good_tab <- merge(good_tab,Uniqueidgender, by = "id")
    good_tab <- merge(good_tab,Uniqueidrace, by = "id")
      good_tab <- merge(good_tab,Uniqueidorgan , by = "id")
        good_tab <- merge(good_tab,Uniqueidquarter , by = "id")
          good_tab <- merge(good_tab,Uniqueidyear , by = "id")
head(good_tab)
dim(Uniqueidlt2)
dim(Uniqueidgender)
dim(Uniqueidrace)
```


```{r}
library(tableone)
# Make a table one #



# uses library(tableone) #
### Table 1 for full/original cohort with none dropped ###
Table01 <- CreateTableOne(data = dat, vars = c('lt2','gender','race','organ','quarter','year') , strata = 'event', factorVars = c('lt2','gender','race','organ','quarter','year'))

#create table with values for overall N #
FullTable01 <- CreateTableOne(data = dat, vars = c('lt2','gender','race','organ','quarter','year') , strata = 'event', factorVars = c('lt2','gender','race','organ','quarter','year'))
FinalTable01 <- print(Table01, quote = FALSE, noSpaces = TRUE, printToggle = FALSE)

write.csv(FinalTable01, file = "Table01_Thesis.csv")
```



```{r}
library(xtable)
lt2_tab <- xtable(as.data.frame(count(Uniqueidlt2$lt2)))
print(lt2_tab, type = "latex")

gender_tab <-xtable(as.data.frame(Uniqueidgender$gender))
print(gender_tab, type = "latex")

race_tab <-xtable(as.data.frame(Uniqueidrace$race))
print(race_tab, type = "latex")

organ_tab <-xtable(as.data.frame(Uniqueidorgan$organ))
print(organ_tab, type = "latex")

q_tab <-xtable(as.data.frame(Uniqueidquarter$quarter))
print(q_tab, type = "latex")

y_tab <-xtable(as.data.frame(Uniqueidyear$year))
print(y_tab , type = "latex")

```

