---
title: "Winslow_Thesis_Joint_Model"
author: "James Winslow"
date: "4/7/2020"
output: pdf_document
---
```{r Import_Data}
library(dplyr)
library(reshape)
source("Winslow_Functions.R")

# this function creates a global object called thesis_data #
# make sure this isn't problematic since using '<<-' isn't a great habit #

import_data("local")


# this function creates a global object called Reshaped & cast_thesis #
# make sure this isn't problematic since using '<<-' isn't a great habit #

clean_data(thesis_data)
clean_up(Reshaped)

```


We want to construct a poisson model for the number of infections observed up to a certain time. By imposing an offset, we can interpret the model as a rate instead of a count. This is beneficial to manage the variable start times that subjects may have  

$log(\lambda_{x}) = log(t_{x}) + \beta^{'}_{0} + \beta^{x}_{1}$ \newline
where $log(t_{x})$ is the offset.


```{r}
library(car)
library(tidyr)

### Relevel / recode for reference categories #

# Make 'Heart' the reference category for organ transplant #

Reshaped$organ <- as.factor(Reshaped$organ)
Reshaped <- within(Reshaped, organ <- relevel(organ, ref = 'Heart'))

# Make the mode (White) the reference category #
Reshaped$race <- as.factor(Reshaped$race)

Reshaped <- within(Reshaped, race <- relevel(race, ref = 'White'))


```






```{r}
# Now, we attempt to code the likelihood function and apply to the data
# looks right #
# head(simple_model)

# write likelihood function for the simple model #
# we have six covariates to model in Z:
# hospital + gender + race + organ + year + lt2
# 

jointpanel.llik <- function(theta,n.events,time.to.death,dead,z) {

  h <- n.events
  t <- time.to.death
  delta <- dead


  lambda <- exp(theta[1])
  mu <- exp(theta[2])
  alpha <- exp(theta[3])


  sum(lgamma(h+alpha+delta) + alpha*log(alpha) - lfactorial(h) - lgamma(alpha) +
    delta*log(mu)+h*log(lambda*t) +(-h-alpha-delta)*log(alpha+t*(mu+lambda)))

}
```

 
```{r}
# give the model starting values for theta
# number should match intercept + each level 
# we can use the 'separate' models for starting values
# can use frailty starting value as 0 or 
start.beta <- rep(0,3)
mod1 <- optim(start.beta, # starting values
 jointpanel.llik, # function to optimize
 hessian=TRUE, # so we can get standard errors
 # arguments to the log-likelihood function
 n.events = simple_model$n.events ,
 time.to.death = simple_model$time.to.death ,
 dead = simple_model$dead , # optimization method (quasi-Newton)
 
 control=list(fnscale=-1,trace=0,maxit=1e3) # tells optim() to maximize instead of minimize
 )

 mod1$par

```


```{r}
library(survival)

joint.llik.cov <- function(theta,N,y,delta,z) {
	# N is count of infections
	# y is time observed
	# delta is 1 if subject died during study, 0 otherwise
	# z is covariate matrix (no column of 1s)
  
  # get all but last element of the vector theta
	regcoef <- head(theta,-1)
	# exponentiate only the last value of the vector theta #
	omega <- exp(tail(theta,1))

	alphacoef <- head(regcoef,length(regcoef)/2)
	betacoef <- tail(regcoef,length(regcoef)/2)
	
	# print(alphacoef)
	# print(betacoef)
	# print(dim(z))

  lambda0 <- exp(z %*% betacoef)
	mu0 <-  exp(z %*% alphacoef)
	
	# lambda0 <- exp(betacoef %*% cbind(1,z))
	# mu0 <-  exp(alphacoef %*% cbind(1,z))

	sum(delta*log(lambda0) + omega*log(omega) - lgamma(omega) + 
	      N*log(mu0*y) - lfactorial(N) + lgamma(N+delta+omega) - 
	      (N+delta+omega)*log(mu0*y+lambda0*y+omega)
	    )


}

z <- model.matrix(~ gender + race + organ + year + lt2, data = Reshaped)
z_new <- attr(z,"assign")

# i have tried maxit=1e3
#              maxit=1e4
#             
	mod1 <- optim(rep(0,23), joint.llik.cov, hessian=TRUE, N=Reshaped$n.events, y=Reshaped$time.to.death, delta=Reshaped$dead, z=z,
		control=list(fnscale=-1,trace=0,maxit=1e5))


mod1
# use diag to solve the negative 
```




